=== oksana89/qborrow/src/test/resources/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"  targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">


 <element name="Oggetto" type="tns:oggetti"></element>
    
    <complexType name="oggetti">
    	<sequence>
    		<element name="Id" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="proprietario" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="titolo" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="descrizione" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="immagine" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="categoria" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="data_ultima_modifica" type="date"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <element name="Soggetto" type="tns:soggetti"></element>
    <complexType name="soggetti">
    	<sequence>
    		<element name="user_name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="email" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="ragione_sociale" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="nome" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="cognome" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="immagine" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="data_ultima_modifica" type="date" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <element name="Prestito" type="tns:prestiti"></element>
    
    <complexType name="prestiti">
    	<sequence>
    		<element name="beneficiario" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="oggetto_prestato" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="data_prestito" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="data_scadenza_prestito" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>


    <complexType name="qborrow">
    	<sequence>
    		<element name="oggetto" type="tns:oggetti" maxOccurs="1" minOccurs="0"></element>
    		<element name="soggetto" type="tns:soggetti" maxOccurs="1" minOccurs="0"></element>
    		<element name="prestiti" type="tns:prestiti" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <element name="qborrow" type="tns:qborrow"></element>
</schema>

=== oksana89/qborrow/src/test/resources/qborrow.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:qborrow xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd">
	
	<tns:oggetto>
		<tns:Id>20</tns:Id>
		<tns:proprietario>oksana</tns:proprietario>
		<tns:titolo>libro</tns:titolo>
		<tns:descrizione>interessante</tns:descrizione>
		<tns:immagine>img</tns:immagine>
		<tns:categoria>lbri e giornali</tns:categoria>
		<tns:data_ultima_modifica>2017-10-13</tns:data_ultima_modifica>
	</tns:oggetto>
	
	<tns:soggetto>
		<tns:user_name>Oksana</tns:user_name>
		<tns:email>oksi.kom89@gmail.com</tns:email>
		<tns:ragione_sociale>OKS</tns:ragione_sociale>
		<tns:nome>oksana</tns:nome>
		<tns:cognome>komarnytska</tns:cognome>
		<tns:immagine>img</tns:immagine>
		<tns:data_ultima_modifica>2017-10-16</tns:data_ultima_modifica>
	</tns:soggetto>
	
	<tns:prestiti>
	<tns:beneficiario>oksana</tns:beneficiario>
		<tns:oggetto_prestato>libro</tns:oggetto_prestato>
		<tns:data_prestito>17/10/2017</tns:data_prestito>
		<tns:data_scadenza_prestito>17/11/12017</tns:data_scadenza_prestito>
	</tns:prestiti>
</tns:qborrow>
